import math

from pyglm import glm

SCREEN_DIMENSIONS = (1920, 1080)
GLOBAL_OCCLUDER_DIMENSIONS = (3500, 400, 3000)
CENTER = glm.vec3(0, 0, 0) * 0.5
ASPECT_RATIO = SCREEN_DIMENSIONS[0] / SCREEN_DIMENSIONS[1]
CAMERA_FAR = 10_000.0
CAMERA_NEAR = 1.0
CAMERA_FOV = 74

USE_VOXEL_OBJECT_INSTANCING = True
VOXEL_OBJECT_COUNT_PER_BATCH = 1000
MAX_VOXEL_OBJECTS = 5000
GLOBAL_DEFINE = {
    "SCREEN_DIMENSIONS": f"vec2({SCREEN_DIMENSIONS[0]}, {SCREEN_DIMENSIONS[1]})",
    "MAX_MIP_LEVELS": 1 + math.floor(math.log2(max(GLOBAL_OCCLUDER_DIMENSIONS))),
    "CAMERA_FAR": CAMERA_FAR,
    "USE_VOXEL_OBJECT_INSTANCING": "1" if USE_VOXEL_OBJECT_INSTANCING else "0",
}

LIGHT_TYPE_NUM_SUN = 0
LIGHT_TYPE_NUM_SPHERE = 1
LIGHT_TYPE_NUM_CONE = 2
LIGHT_TYPE_NUM_AREA = 3
