from pyglm import glm

SCREEN_DIMENSIONS = (1920, 1080)
GLOBAL_OCCLUDER_DIMENSIONS = (256, 256, 256)
CENTER = glm.vec3(GLOBAL_OCCLUDER_DIMENSIONS) * 0.5
CENTER_GROUND = glm.vec3(GLOBAL_OCCLUDER_DIMENSIONS) * 0.5
CENTER_GROUND.y = 0
ASPECT_RATIO = SCREEN_DIMENSIONS[0] / SCREEN_DIMENSIONS[1]
GLOBAL_DEFINE = {
    "SCREEN_DIMENSIONS": f"vec2({SCREEN_DIMENSIONS[0]}, {SCREEN_DIMENSIONS[1]})",
}
